### ISSUE TITLE
Contao 4.6

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-upload_filename_sanitizer#1]
Hallo,
ich bin auf diese Extension aufmerksam gemacht worden. Beim Testen ist mir beim Erstellen von Ordnern im Backend aufgefallen, dass Umlaute nicht in ascii geändert werden.
![grafik](https://user-images.githubusercontent.com/1572887/45234618-95286c80-b2d6-11e8-9bab-2cc1f46994be.png)
![grafik](https://user-images.githubusercontent.com/1572887/45234629-9bb6e400-b2d6-11e8-9864-2f651a6b6c54.png)

**Comment by Defcon0** [comment]
Hallo,

wir nutzen für das Sanitizing des Dateinamens am Ende die Funktion `standardize` von Contao. Diese lässt die Umlaute drin.

Wenn Sie möchten, könnten Sie den Callback (https://github.com/heimrichhannot/contao-upload_filename_sanitizer/blob/master/dca/tl_files.php) entsprechend abändern und per str_replace alle Vorkommen von Umlauten ersetzen, also so:

```
return str_replace(['ä', 'ö', 'ü'], ['ae', 'oe', 'ue'], \HeimrichHannot\Haste\Util\Files::sanitizeFileName($varValue));
```
