### ISSUE TITLE
Umlautersetzung

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-upload_filename_sanitizer#2]
Vielen Dank für die Info.
Wenn Sie die Contao standardize Funktion nutzen, sollten Sie die readme.md ändern, denn dort versprechen Sie die Umlautersetzung auch beim Anlegen von Ordnern an.

**Comment by Defcon0** [comment]
In Contao 3, für das das Modul auch geeignet ist, ist das auch noch so ;-) Ich glaube, das wurde in Contao 4 geändert, bin mir aber nicht sicher.

**Comment by chriza** [comment]
Ab Contao 4.5 ist es möglich im Webseitenstartpunkt einer Webseite die ALIAS Einstellungen zu modifizieren. Wäre es möglich, diese Einstellung in die Extension zu integrieren?

![grafik](https://user-images.githubusercontent.com/1572887/45373863-bba91900-b5f0-11e8-95c4-6f65ce50b74e.png)

**Comment by Defcon0** [comment]
Es wird bald eine Bundle-Variante geben, in der die erlaubten Zeichen eingestellt werden können.

**Comment by chriza** [comment]
Habe die neue Extension schon eingesetzt. Super! Vielen lieben Dank :o)

**Comment by Defcon0** [comment]
Danke für die Rückmeldung, freut mich zu hören ;-) Viel Spaß damit!
