### ISSUE TITLE
php-iban

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-upload_filename_sanitizer#3]
Die Extension installiert globalcitizen/php-iban.
Ist das notwendig?

**Comment by Defcon0** [comment]
Hallo,

die Erweiterung braucht heimrichhannot/contao-haste_plus. Und diese wiederum braucht php-iban. Es wird allerdings in Bälde eine etwas aufgeräumtere und konfigurierbarere Variante geben. Diese wird dann contao-utils-bundle nutzen, wo in jedem Fall globalcitizen/php-iban keine Abhängigkeit mehr sein wird ;-)
