### ISSUE TITLE
Einträge im Header

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-upload_filename_sanitizer#4]
Nach Installation der Extension wird folgendes in den Header geschrieben:

![grafik](https://user-images.githubusercontent.com/1572887/45374061-50137b80-b5f1-11e8-9379-12ed4e2cb0a5.png)

Das dürfte nicht DSVGO konform sein.

**Comment by Defcon0** [comment]
Hallo @chriza ,

ich habe das neue Bundle fertiggestellt. Dort kann nun wesentlich genauer eingestellt werden, was gemacht wird. Es handelt sich auch um ein Contao 4 Bundle in der neuen Struktur:

https://github.com/heimrichhannot/contao-filename-sanitizer-bundle

Das o.g. Problem ist damit auch erledigt.
