### ISSUE TITLE
Contao 4.6.13: overwriting files leads to deletion on sync

### ISSUE THREAD

**Issue by johannes-bittner** [heimrichhannot/contao-upload_filename_sanitizer#5]
If you upload a file with the same file name in the file explorer in a given directory, the existing file should simply be overwritten and the UUID should stay the same. With contao-upload_filename_sanitizer installed, I was able to reproduce the following behavior: 
- upload document testdoc.txt: existing document testdoc.txt gets overwritten
- execute sync outputs the message: testdoc.txt was deleted
- nevertheless, testdoc.txt still exists in the give directory, but links to that file are broken (e.g. for downloads, other extension assets, linked images etc.)

**Comment by Defcon0** [comment]
Could you please check if the problem also exists in https://github.com/heimrichhannot/contao-filename-sanitizer-bundle as this module here is abandoned and not maintainted anymore.

I also just fixed the readme to inform about that.

**Comment by johannes-bittner** [comment]
hm, doesn't look that good, tried multiple times and with different files: 
![grafik](https://user-images.githubusercontent.com/1597697/52644065-7a3dd200-2ede-11e9-81d6-271af067aa6f.png)
(although the file is still there!)
I'll open an issue in [https://github.com/heimrichhannot/contao-filename-sanitizer-bundle](https://github.com/heimrichhannot/contao-filename-sanitizer-bundle)

**Comment by Defcon0** [comment]
OK, thanks.
